// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1XdOjyIIjEXrnb_Ki6KcbKWKN6geKXs0',
    appId: '1:100644747964:web:44af95a5c49397ae6a6eb9',
    messagingSenderId: '100644747964',
    projectId: 'e-com83',
    authDomain: 'e-com83.firebaseapp.com',
    storageBucket: 'e-com83.firebasestorage.app',
    measurementId: 'G-ERRKSSVL80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA25eT02K6tSz8fq_hvUm-I43lE6RMyHyI',
    appId: '1:100644747964:android:ff84e93a8189df706a6eb9',
    messagingSenderId: '100644747964',
    projectId: 'e-com83',
    storageBucket: 'e-com83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaC6TdXDlBSbP-76ORdG3F9kjhyt8KTbI',
    appId: '1:100644747964:ios:b7c12c59b89389946a6eb9',
    messagingSenderId: '100644747964',
    projectId: 'e-com83',
    storageBucket: 'e-com83.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaC6TdXDlBSbP-76ORdG3F9kjhyt8KTbI',
    appId: '1:100644747964:ios:b7c12c59b89389946a6eb9',
    messagingSenderId: '100644747964',
    projectId: 'e-com83',
    storageBucket: 'e-com83.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1XdOjyIIjEXrnb_Ki6KcbKWKN6geKXs0',
    appId: '1:100644747964:web:c5cc1509fb0e348f6a6eb9',
    messagingSenderId: '100644747964',
    projectId: 'e-com83',
    authDomain: 'e-com83.firebaseapp.com',
    storageBucket: 'e-com83.firebasestorage.app',
    measurementId: 'G-6HQFRB3YGG',
  );
}
